// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtXtz5rUEhcE2D6IQ4U7NobIY_f7h_hSE',
    appId: '1:376359430627:web:b41276ddd04b74c9d5d8d6',
    messagingSenderId: '376359430627',
    projectId: 'aiconverse-chatbot-app',
    authDomain: 'aiconverse-chatbot-app.firebaseapp.com',
    storageBucket: 'aiconverse-chatbot-app.appspot.com',
    measurementId: 'G-F4E1LPL3CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhOtscQMxmzjRGx1XB5OvBQfJCfnNL4ZA',
    appId: '1:376359430627:android:827cba4b8b16e024d5d8d6',
    messagingSenderId: '376359430627',
    projectId: 'aiconverse-chatbot-app',
    storageBucket: 'aiconverse-chatbot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeogZOtUsikmiID0DFSkJ1H3OUTGv2ng4',
    appId: '1:376359430627:ios:d9074e8f6facf40ed5d8d6',
    messagingSenderId: '376359430627',
    projectId: 'aiconverse-chatbot-app',
    storageBucket: 'aiconverse-chatbot-app.appspot.com',
    iosBundleId: 'com.example.aiConverseChatbotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeogZOtUsikmiID0DFSkJ1H3OUTGv2ng4',
    appId: '1:376359430627:ios:7ea0e81ab495b936d5d8d6',
    messagingSenderId: '376359430627',
    projectId: 'aiconverse-chatbot-app',
    storageBucket: 'aiconverse-chatbot-app.appspot.com',
    iosBundleId: 'com.example.aiConverseChatbotApp.RunnerTests',
  );
}
